apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-demo-portal
  namespace: {{ .Release.Namespace }}
  labels:
    app: fc-demo-portal
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      app: fc-demo-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fc-demo-portal
    spec:
      containers:
        - name: fc-demo-portal
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FC_CLIENT_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fc-keycloak-client-secret
                  key: keycloak_client_secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "https://{{ .Values.keycloakHost }}/auth/realms/gaia-x"
            - name: FEDERATED_CATALOGUE_BASE_URI
              value: {{ .Values.portal.fcBaseUri }}
          ports:
            - name: http
              containerPort: 8088
          readinessProbe:
            httpGet:
              path: {{ .Values.portal.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.portal.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.portal.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.portal.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
